AWSTemplateFormatVersion: '2010-09-09'
Description: Route 53 hosted zone with DNSSEC enabled
Resources:
  MyHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: example.com
  MyDNSSEC:
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref MyHostedZone
