AWSTemplateFormatVersion: '2010-09-09'
Description: Create a new KMS key for encryption
Resources:
  MyKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "My KMS Key for encryption"
      KeyUsage: ENCRYPT_DECRYPT
      Origin: AWS_KMS
      Enabled: true
