apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: source-bucket
spec:
  bucketName: source-bucket
  logging:
    targetBucket: central-logging-bucket
    targetPrefix: "source-bucket-logs/"
