AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with an owner tag
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0abcdef1234567890
